# Name : Ram Darekar
# Roll No : 114
# Div : B

In [56]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [57]:
df=pd.read_csv('data.csv')

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   str
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   str
 15  city           4600 non-null   str
 16  statezip       4600 non-null   str
 17  country        4600 non-null   str
dtypes: float64(4), int64(9), str(5)
memory usage: 647.0 KB

In [59]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [60]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

In [61]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [62]:
df=df.drop(['date'],axis=1)

In [63]:
df=df.drop(['street'],axis=1)

In [64]:
df=df.drop(['city'],axis=1)

In [65]:
df=df.drop(['country'],axis=1)

In [66]:
df=df.drop(['statezip'],axis=1)

In [67]:
X = df.drop('price', axis=1)
y = df['price']

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [70]:
from sklearn.preprocessing import StandardScaler

In [71]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [72]:
from tensorflow.keras.models import Sequential

In [73]:
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential([
    Dense(32, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(1, activation='linear')   
])

d:\Advanced data science Lab\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [75]:
model.compile(optimizer='adam',
              loss='mse',              # 'binary_crossentropy' for classification
              metrics=['mae'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [76]:
history = model.fit(X_train, y_train, epochs=50,
                     batch_size=16, validation_split=0.2)

Epoch 1/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 448293863424.0000 - mae: 546850.1875 - val_loss: 401486807040.0000 - val_mae: 536791.3750
Epoch 2/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 448196018176.0000 - mae: 546783.9375 - val_loss: 401301012480.0000 - val_mae: 536656.7500
Epoch 3/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 447821611008.0000 - mae: 546536.8125 - val_loss: 400800251904.0000 - val_mae: 536298.5000
Epoch 4/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 446966726656.0000 - mae: 545984.4375 - val_loss: 399749054464.0000 - val_mae: 535558.5000
Epoch 5/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 445350936576.0000 - mae: 544979.9375 - val_loss: 397998784512.0000 - val_mae: 534333.1250
Epoch 6/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 442893893632.0000 - mae: 543426.6250 - val_loss: 395493310464.0000 - val_mae: 532582.0625
Epoch 7/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 439557455872.0000 - mae: 541335.0625 - val_loss: 392209858560.0000 - val_mae: 530284.6250
Epoch 8/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 435266355200.0000 - mae: 538683.8125 - val_loss: 388097212416.0000 - val_mae: 527391.9375
Epoch 9/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 430047002624.0000 - mae: 535363.5625 - val_loss: 383244075008.0000 - val_mae: 523954.5938
Epoch 10/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 423965523968.0000 - mae: 531436.4375 - val_loss: 377608437760.0000 - val_mae: 519925.1875
Epoch 11/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 416939245568.0000 - mae: 526925.8125 - val_loss: 371196559360.0000 - val_mae: 515287.9062
Epoch 12/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 408823595008.0000 - mae: 521746.3438 - val_loss: 363785715712.0000 - val_mae: 509877.3125
Epoch 13/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 399659368448.0000 - mae: 515683.1875 - val_loss: 355451502592.0000 - val_mae: 503713.7500
Epoch 14/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 389688164352.0000 - mae: 508943.6875 - val_loss: 346603454464.0000 - val_mae: 497029.5625
Epoch 15/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 378912931840.0000 - mae: 501674.6875 - val_loss: 337010786304.0000 - val_mae: 489645.0938
Epoch 16/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 367297724416.0000 - mae: 493760.3125 - val_loss: 326634962944.0000 - val_mae: 481479.9062
Epoch 17/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 355016572928.0000 - mae: 484845.0000 - val_loss: 315884339200.0000 - val_mae: 472786.1250
Epoch 18/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 342261465088.0000 - mae: 475431.3438 - val_loss: 304918822912.0000 - val_mae: 463639.3438
Epoch 19/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 329008283648.0000 - mae: 465518.8750 - val_loss: 293153865728.0000 - val_mae: 453552.3438
Epoch 20/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 315349401600.0000 - mae: 454922.2500 - val_loss: 281330941952.0000 - val_mae: 443050.0938
Epoch 21/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 301608042496.0000 - mae: 443706.0938 - val_loss: 269462781952.0000 - val_mae: 432121.0938
Epoch 22/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 287851642880.0000 - mae: 432253.6562 - val_loss: 257676935168.0000 - val_mae: 420810.4688
Epoch 23/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 274159730688.0000 - mae: 420478.2500 - val_loss: 245919203328.0000 - val_mae: 409088.0000
Epoch 24/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 260710940672.0000 - mae: 408425.1875 - val_loss: 234451107840.0000 - val_mae: 397355.3438
Epoch 25/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 247485038592.0000 - mae: 396180.6562 - val_loss: 223035654144.0000 - val_mae: 385277.8125
Epoch 26/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 234695835648.0000 - mae: 383541.3125 - val_loss: 212076134400.0000 - val_mae: 373215.5312
Epoch 27/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 222499684352.0000 - mae: 371201.5312 - val_loss: 201718300672.0000 - val_mae: 361559.1875
Epoch 28/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 211014664192.0000 - mae: 359034.1875 - val_loss: 191933431808.0000 - val_mae: 350230.5938
Epoch 29/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 200183185408.0000 - mae: 347183.9062 - val_loss: 182716448768.0000 - val_mae: 339516.6875
Epoch 30/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 190030118912.0000 - mae: 335865.9688 - val_loss: 174058536960.0000 - val_mae: 329142.3125
Epoch 31/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 180630601728.0000 - mae: 325195.7812 - val_loss: 165937233920.0000 - val_mae: 319285.9062
Epoch 32/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 171942133760.0000 - mae: 315100.8125 - val_loss: 158596481024.0000 - val_mae: 310228.2500
Epoch 33/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 164059693056.0000 - mae: 305380.7812 - val_loss: 151681368064.0000 - val_mae: 301456.1562
Epoch 34/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 156947791872.0000 - mae: 296702.0625 - val_loss: 145635655680.0000 - val_mae: 293657.3125
Epoch 35/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 150656204800.0000 - mae: 288673.7500 - val_loss: 140103254016.0000 - val_mae: 286322.4062
Epoch 36/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 145133305856.0000 - mae: 281256.5938 - val_loss: 135253319680.0000 - val_mae: 279856.1250
Epoch 37/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 140210388992.0000 - mae: 274965.4688 - val_loss: 130937896960.0000 - val_mae: 273795.3750
Epoch 38/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 135810670592.0000 - mae: 268926.4062 - val_loss: 126895996928.0000 - val_mae: 267929.6250
Epoch 39/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 131872743424.0000 - mae: 263529.3750 - val_loss: 123282153472.0000 - val_mae: 262567.9688
Epoch 40/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 128354664448.0000 - mae: 258414.3906 - val_loss: 120034222080.0000 - val_mae: 257668.5625
Epoch 41/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 125212319744.0000 - mae: 253835.0469 - val_loss: 117074141184.0000 - val_mae: 252993.8750
Epoch 42/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 122366287872.0000 - mae: 249396.5156 - val_loss: 114329534464.0000 - val_mae: 248538.8906
Epoch 43/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 119787954176.0000 - mae: 245498.7656 - val_loss: 111852822528.0000 - val_mae: 244474.6094
Epoch 44/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 117405474816.0000 - mae: 241831.0625 - val_loss: 109501267968.0000 - val_mae: 240520.1250
Epoch 45/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 115194863616.0000 - mae: 238213.8438 - val_loss: 107308843008.0000 - val_mae: 236845.4062
Epoch 46/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 113119821824.0000 - mae: 234899.9375 - val_loss: 105249234944.0000 - val_mae: 233365.7344
Epoch 47/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 111199764480.0000 - mae: 231576.1562 - val_loss: 103333437440.0000 - val_mae: 230221.6094
Epoch 48/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 109375381504.0000 - mae: 228615.5625 - val_loss: 101533614080.0000 - val_mae: 227299.2031
Epoch 49/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 107658346496.0000 - mae: 225768.6719 - val_loss: 99795664896.0000 - val_mae: 224438.0938
Epoch 50/50
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 106023616512.0000 - mae: 222968.0156 - val_loss: 98186682368.0000 - val_mae: 221791.4844

In [77]:
results = model.evaluate(X_test, y_test)
print('Test Loss, Test MAE:', results)

29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1048234491904.0000 - mae: 274025.9688
Test Loss, Test MAE: [1048234491904.0, 274025.96875]